pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: self
    - repository: dfc-devops
      type: github
      name: NickGraham101/dfc-devops
      ##TO DO: revert to tag
      ref: refs/heads/AddSetDockerImageTagsScript
      endpoint: NickGraham101

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

stages:
- stage: BuildAndPublishContainer
  variables:
  - group: ContainerRegistryVariables
  jobs:
  - template: JobTemplates\publish-container-image.yml
    parameters:
      ContainerRegistryPassword: $(ContainerRegistryPassword)
      ContainerRegistryAdminUser: $(ContainerRegistryAdminUser)
      ImageName: blogifier