parameters:
  ContainerRegistryPassword: 
  ContainerRegistryAdminUser: 
  ImageName: 

jobs:
- job: BuildAndPublishContainer
  steps:
  - checkout: self
    path: '/'
  - checkout: dfc-devops
    path: 'dfc-devops/'
  - task: gittools.gittools.execute-gitversion-task.gitversion/execute@0
    displayName: gitversion/execute
    inputs:
      useConfigFile: true
      configFilePath: docker/GitVersion.yml
  - task: PowerShell@2
    displayName: 'PowerShell: Set-DockerImageTag'
    inputs:
      targetType: 'filePath'
      filePath: $(Pipeline.Workspace)/dfc-devops/grahamandtonic-dotnet/src/grahamandtonic.scripts/Set-DockerImageTag.ps1
      arguments: -BuildBuildNumber $(GitVersion.MajorMinorPatch) -BuildSourceBranchName $(Build.SourceBranchName) -Verbose
  - script: |
      docker login -u ${{ parameters.ContainerRegistryAdminUser }} -p ${{ parameters.ContainerRegistryPassword }} ${{ parameters.ContainerRegistryAdminUser }}.azurecr.io
      docker build -t ${{ parameters.ImageName }} .
      docker tag ${{ parameters.ImageName }} ${{ parameters.ContainerRegistryAdminUser }}.azurecr.io/${{ parameters.ImageName }}:$(DockerImageTag)
      docker tag ${{ parameters.ImageName }} ${{ parameters.ContainerRegistryAdminUser }}.azurecr.io/${{ parameters.ImageName }}
    displayName: 'Build container'
  - script: |
      docker login -u ${{ parameters.ContainerRegistryAdminUser }} -p ${{ parameters.ContainerRegistryPassword }} ${{ parameters.ContainerRegistryAdminUser }}.azurecr.io
      docker push ${{ parameters.ContainerRegistryAdminUser }}.azurecr.io/${{ parameters.ImageName }}:$(DockerImageTag)
      docker push ${{ parameters.ContainerRegistryAdminUser }}.azurecr.io/${{ parameters.ImageName }}
    displayName: 'Publish container'