parameters:
  ContainerRegistryPassword: 
  ContainerRegistryAdminUser: 
  ImageName: 

jobs:
- job: BuildAndPublishContainer
  steps:
  - checkout: grahamandtonic
    path: grahamandtonic/
  - task: gittools.gitversion.gitversion-task.GitVersion@5
    displayName: GitVersion
    inputs:
      useConfigFile: true
      configFilePath: GitVersion.yml
  - task: PowerShell@2
    displayName: 'PowerShell script: Set-DockerImageTag'
    inputs:
      targetType: 'filePath'
      filePath: $(Pipeline.Workspace)/grahamandtonic/grahamandtonic-dotnet/src/grahamandtonic.scripts/Set-DockerImageTag.ps1
      arguments: -BuildBuildNumber $(GitVersion.MajorMinorPatch) -BuildSourceBranchName $(Build.SourceBranchName) -Verbose
  - script: |
      docker login -u ${{ parameters.ContainerRegistryAdminUser }} -p ${{ parameters.ContainerRegistryPassword }} ${{ parameters.ContainerRegistryAdminUser }}.azurecr.io
      docker build -t ${{ parameters.ImageName }} .
      docker tag ${{ parameters.ImageName }} ${{ parameters.ContainerRegistryAdminUser }}.azurecr.io/${{ parameters.ImageName }}:$(DockerImageTag)
      docker tag ${{ parameters.ImageName }} ${{ parameters.ContainerRegistryAdminUser }}.azurecr.io/${{ parameters.ImageName }}
    displayName: 'Build azure devops  container'
  - script: |
      docker login -u ${{ parameters.ContainerRegistryAdminUser }} -p ${{ parameters.ContainerRegistryPassword }} ${{ parameters.ContainerRegistryAdminUser }}.azurecr.io
      docker push ${{ parameters.ContainerRegistryAdminUser }}.azurecr.io/${{ parameters.ImageName }}:$(DockerImageTag)
      docker push ${{ parameters.ContainerRegistryAdminUser }}.azurecr.io/${{ parameters.ImageName }}
    displayName: 'Publish azure devops  container'